apiVersion: v1
kind: Service
metadata:
  name: jinjafx
  labels:
    app: jinjafx
spec:
  type: ClusterIP
  selector:
    app: jinjafx
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinjafx
spec:
  selector:
    matchLabels:
      app: jinjafx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jinjafx
    spec:
      dnsPolicy: Default
      volumes:
        - name: jinjafx-repository
          hostPath:
            path: /var/lib/jinjafx
      containers:
        - name: jinjafx
          image: docker.io/cmason3/jinjafx:latest
          args: [ "-r", "/var/lib/jinjafx" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jinjafx-repository
              mountPath: /var/lib/jinjafx
          readinessProbe:
            httpGet:
              port: 8080
              path: /ping
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /ping
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5

          env:
            - name: TZ
              value: 'Europe/London'
